[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
toml = "0.8.19"
tracing = "0.1.41"
clap = { version = "4.5.16", features = ["derive"] }
bincode = "1.3.3"
serde = { version = "1.0.216", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
