apiVersion: apps/v1
kind: Deployment
metadata:
  name: walrs-core
  namespace: walrs
  labels:
    app: walrs-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walrs-core
  template:
    metadata:
      labels:
        app: walrs-core
    spec:
      containers:
      - name: walrs-core
        image: localhost:5001/walrs_core:latest
        ports:
        - containerPort: 8080
          name: walrs-core-svc
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: walrs-core-service
  namespace: walrs
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002
    targetPort: walrs-core-svc
  selector:
    app: walrs-core
