apiVersion: v1
kind: Namespace
metadata:
  name: kraft-rs
  labels:
    name: kraft-rs
---
apiVersion: v1
kind: Service
metadata:
  name: kraft-rs-service
  namespace: kraft-rs
  labels:
    app: kraftrs
spec:
  clusterIP: None
  selector:
    app: kraftrs
  ports:
  - protocol: UDP
    port: 5056
    targetPort: 5056
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kraft-rs-local-pv
  namespace: kraft-rs
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /tmp/kraft-rs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker
