apiVersion: v1
kind: Namespace
metadata:
  name: kraft-rs
  labels:
    name: kraft-rs
---
apiVersion: v1
kind: Service
metadata:
  name: kraft-rs-service
  namespace: kraft-rs
  labels:
    app: kraftrs
spec:
  clusterIP: None
  selector:
    app: kraftrs
  ports:
  - protocol: UDP
    port: 5056
    targetPort: 5056
