apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kraft-rs-broker
  namespace: ${PROJECT_NAME}
  labels:
    app: kraftrs
spec:
  serviceName: kraft-rs-service
  replicas: 6
  selector:
    matchLabels:
      app: kraftrs
  template:
    metadata:
      labels:
        app: kraftrs
        role: broker
    spec:
      containers:
      - name: kraftrs
        image: localhost:5001/kraft-rs:${GIT_COMMIT}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 5056
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: kraft-rs-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Mi
