{
 "title": "walrs-monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Latest values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network utilization in mb/s",
   "type": "gauge",
   "description": "by pods",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_network_receive_bytes_total{namespace=\"walrs\"}[5m]) +\n  rate(container_network_transmit_bytes_total{namespace=\"walrs\"}[5m])\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory consumption in MB",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=\"walrs\"}) by (pod) / 1024 ) / 1024  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"walrs\"}[5m])) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Network utilization in mb/s",
   "type": "timeseries",
   "description": "by pods",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_network_receive_bytes_total{namespace=\"walrs\"}[5m]) +\n  rate(container_network_transmit_bytes_total{namespace=\"walrs\"}[5m])\n) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory consumption in MB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{namespace=\"walrs\"}) by (pod) / 1024 ) / 1024  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"walrs\"}[5m])) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}